description: gaminax computing blog
google_analytics: UA-73093345-1
baseurl: "/computingBlog"
github_username: gaminax
author: gaminax
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-asciidoc

asciidoc:
    ext: ad, adoc, asciidoc

